### ISSUE TITLE
error installing uploadPics module

### ISSUE THREAD

**Issue by mblau54937** [sdetweil/uploadPics#3]
magicmirror@magicmirror:~/MagicMirror/modules/uploadPics$ npm install

> uploadPics@1.0.0 postinstall
> ./postinstall

dpkg-deb: error: unexpected end of file in archive magic version number in xx.deb
dpkg: error processing archive xx.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 xx.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
exiftran is already the newest version (2.10-4ubuntu4).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.

up to date, audited 30 packages in 5s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by sdetweil** [comment]
can you show me output of

lsb_release -a
uname -a

**Comment by mblau54937** [comment]
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble

uname -a
Linux magicmirror 6.8.0-47-generic #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 21:40:26 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sdetweil** [comment]
please go to the module folder and

```
git pull
npm install
```

please advise your results.

**Comment by mblau54937** [comment]
It appears to be working now. Thank you!Regards,MattOn Oct 24, 2024, at 3:23 PM, sam detweiler ***@***.***> wrote:﻿
please go to the module folder and
git pull
npm install

please advise your results.

**Comment by sdetweil** [comment]
awesome
